---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-deployment
  labels:
    app: bookapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dc
                operator: In
                values:
                - DC2
      containers:
      - name: bookapi
        image: bonifacekabaso/bookapi:0.0.1
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: bookapi-service
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 9000
     nodePort: 30250
  selector:
     app: bookapi
